services:
  web-labo3:
    build: .
    command: sh /app/entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app
      DJANGO_SETTINGS_MODULE: config.settings
    depends_on:
      db-labo3:
        condition: service_healthy
    volumes:
      - .:/app

  db-labo3:
    image: postgres:15
    environment:
      POSTGRES_DB: lab3db
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "labuser", "-d", "lab3db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
